/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  Auth: {
    Cognito: {
      region: 'us-east-1',
      userPoolClientId: '4hunpseqrudpp53p102oo9246d',
      region: 'us-east-1',
      userPoolId: 'us-east-1_XAjJXycrx',
      oauth: {
        domain: 'beatsheet-manager-app.auth.us-east-1.amazoncognito.com',
        scope: ['email', 'profile', 'openid'],
        redirectSignIn: 'http://beetsheet-app.s3-website-us-east-1.amazonaws.com/beatsheets',
        redirectSignOut: 'http://beetsheet-app.s3-website-us-east-1.amazonaws.com',
        responseType: 'code',
      }
    }
  }
};

export default awsmobile;
